services:
  node1:
    build: ./docker/glusterfs-node/
    privileged: true
    environment:
      - GLUSTERFS_NODE_NAME=node1
    volumes:
      - .:/app

  node2:
    build: ./docker/glusterfs-node/
    privileged: true

  node3:
    build: ./docker/glusterfs-node/
    privileged: true