name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running test env
        run: docker compose up -d
      - name: Setting up test cluster
        run: \
          docker compose exec node1 mkdir -p /mnt/brick1/brick &&\
          docker compose exec node2 mkdir -p /mnt/brick1/brick &&\
          docker compose exec node3 mkdir -p /mnt/brick1/brick \
      - name: Running tests
        working-directory: ./test
        run: go test -v
      - name: Stopping test env
        run: docker compose down